name: CI

on:
  push:
    branches:
      - main
      - feature/fix-tests

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12, 3.11, 3.12]
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: cria
          MYSQL_DATABASE: criadex
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      qdrant:
        image: qdrant/qdrant:v1.9.6
        ports:
          - "6333:6333"
          - "6334:6334"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-dotenv # Install pytest and plugins

    - name: Create .env file with required variables
      run: |
        cat <<EOF > .env
        QDRANT_HOST=localhost
        QDRANT_PORT=6333
        QDRANT_GRPC_PORT=6334
        QDRANT_API_KEY=NONE
        MYSQL_HOST=localhost
        MYSQL_PORT=3306
        MYSQL_USERNAME=root
        MYSQL_PASSWORD=cria
        MYSQL_DATABASE=criadex_test
        APP_INITIAL_MASTER_KEY=password
        TEST_MASTER_KEY=password
        TEST_NON_MASTER_KEY=password-nomaster
        TEST_DOCUMENT_GROUP=test-document-index
        TEST_QUESTION_INDEX=test-question-index
        TEST_LLM_ID=1
        TEST_EMBEDDING_ID=2
        TEST_RERANKER_ID=1
        APP_API_MODE=TESTING
        EOF

    - name: Wait for services (MySQL & Qdrant)
      shell: bash
      run: |
        echo "Waiting for MySQL..."
        for i in {1..60}; do
          if mysqladmin ping -h 127.0.0.1 -uroot -pcria --silent; then echo "MySQL is ready"; break; fi; sleep 1; done
        echo "Waiting for Qdrant..."
        for i in {1..60}; do
          if curl -sf http://127.0.0.1:6333/healthz >/dev/null; then echo "Qdrant is ready"; break; fi; sleep 1; done

    - name: Run tests
      env:
        QDRANT_HOST: localhost
        QDRANT_PORT: 6333
        QDRANT_GRPC_PORT: 6334
        QDRANT_API_KEY: NONE
        MYSQL_HOST: localhost
        MYSQL_PORT: 3306
        MYSQL_USERNAME: root
        MYSQL_PASSWORD: cria
        MYSQL_DATABASE: criadex_test
        APP_INITIAL_MASTER_KEY: password
        TEST_MASTER_KEY: password
        TEST_NON_MASTER_KEY: password-nomaster
        TEST_DOCUMENT_GROUP: test-document-index
        TEST_QUESTION_INDEX: test-question-index
        TEST_LLM_ID: 1
        TEST_EMBEDDING_ID: 2
        TEST_RERANKER_ID: 1
        APP_API_MODE: TESTING
      run: |
        # Run tests
        pytest -s -v test