name: CI

on:
  push:
    branches:
      - main
      - feature/fix-tests

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: cria
          MYSQL_DATABASE: criadex
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      qdrant:
        image: qdrant/qdrant:v1.9.6
        ports:
          - "6333:6333"
          - "6334:6334"
        options: >-
          --health-cmd "curl -f http://localhost:6333/healthz || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-dotenv # Install pytest and plugins

    - name: Run tests
      run: |
        # Set environment variables for testing
        echo "APP_API_MODE=TESTING" >> $GITHUB_ENV
        echo "QDRANT_HOST=localhost" >> $GITHUB_ENV
        echo "QDRANT_PORT=6333" >> $GITHUB_ENV
        echo "QDRANT_GRPC_PORT=6334" >> $GITHUB_ENV
        echo "QDRANT_API_KEY=NONE" >> $GITHUB_ENV
        echo "MYSQL_HOST=localhost" >> $GITHUB_ENV
        echo "MYSQL_PORT=3306" >> $GITHUB_ENV
        echo "MYSQL_USERNAME=root" >> $GITHUB_ENV
        echo "MYSQL_PASSWORD=cria" >> $GITHUB_ENV
        echo "MYSQL_DATABASE=criadex_test" >> $GITHUB_ENV
        echo "APP_INITIAL_MASTER_KEY=password" >> $GITHUB_ENV
        echo "TEST_MASTER_KEY=password" >> $GITHUB_ENV
        echo "TEST_NON_MASTER_KEY=password-nomaster" >> $GITHUB_ENV
        echo "TEST_DOCUMENT_GROUP=test-document-index" >> $GITHUB_ENV
        echo "TEST_QUESTION_INDEX=test-question-index" >> $GITHUB_ENV
        echo "TEST_LLM_ID=1" >> $GITHUB_ENV
        echo "TEST_EMBEDDING_ID=2" >> $GITHUB_ENV
        echo "TEST_RERANKER_ID=1" >> $GITHUB_ENV

        # Run tests
        pytest -s -v test